version: '3.8'

services:
  app:
    build:
      context: ./container
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  mailhog:
    build:
      context: ./container/mailhog
      dockerfile: Dockerfile
    ports:
      - "1025:1025"
      - "8025:8025"
