version: '3'

services:
  # Service Node.js
  web:
    image: node:18-alpine
    build: ./Mailer
    working_dir: /usr/src/app
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
    command: ["npm", "run", "start:prod"]
    volumes:
      - ./Mailer:/usr/src/app

   # service mailer hog

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
   