FROM mysql:latest

# Environnement pour le mot de passe root, le nom de la base de données et les identifiants utilisateur
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=foiredeMarseille
ENV MYSQL_USER=root2
ENV MYSQL_PASSWORD=1234

# Copie d'un fichier SQL de configuration ou de seed (facultatif)
# COPY ./init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306
