version: '3.5'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: FOIREDEMARSEILLE
    volumes:
      - my-db:/var/lib/postgresql/data
    ports:
      - '5433:5432' # Changer le port à 5433

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8083:80"  # Changer le port à 8083
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root

volumes:
  my-db: