ersion: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    env_file:
      - database.env
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - '4444:80'
        restart: always
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
