version: '3.8'

services:
  web:
    image: node:18-alpine
    build: .
    working_dir: /usr/src/app
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
    command: ["npm", "run", "start:prod"]
    volumes:
      - .:/usr/src/app
