version: '3.9'

services:
  web:
    image: node:18-alpine
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
    command: ["npm", "run", "start:prod"]
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
      - /usr/src/app/node_modules
